#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    password: Pthakare@27
#    url: jdbc:mysql://localhost:3306/employeedetail
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysqldb:3306/employeedetail
#    username: root
#    password: Pthakare@27
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
    
#spring.jppa.properties.hibernate.dialect =  org.hibernate.dialect.MySQL8Dialect

      