version: "3"
services:
  application:
    image: SpringBootNewPrograam
    networks:
      - springboot-db-net
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: Pthakare@27
      MYSQL_DB: employeedetail
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=Pthakare@27
      - MYSQL_DATABASE=employeedetail
networks:
  - springboot-db-net:
