version: "3"
services:
  application:
    image: SpringBootNewPrograam
    networks:
      - springboot-db-net
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Pthakare@27
networks:
  - springboot-db-net: